### ISSUE TITLE
Mongoose variable name difference in esm and cjs templates

### ISSUE THREAD

**Issue by KeithanPhilander** [code-collabo/node-mongo-cli#134]
Sooo.. not a bug but wasn't sure if I should be dishing out tasks here just yet

So reading through the [setup](https://code-collabo.gitbook.io/node-mongo/boilerplate-templates) for the boilerplate template I came across this naming disparity between the code and the docs

![documentation](https://user-images.githubusercontent.com/29425128/135727802-410e1e7e-23db-407b-b710-15bef8bb1aaa.png)

![code](https://user-images.githubusercontent.com/29425128/135727804-6c213479-2681-4b75-be2b-10fb77e0a1ac.png)

Not sure if this is a known issue or if it's intentional just putting it out there.

**Comment by Ifycode** [comment]
Oh! Nice catch. Actually, it's correct. but only correct for the esm template. I was dealing with the esm template at the time and totally forgot that the export name is different for cjs template. Thank you. 
Will you be willing to send a PR to fix this? - just change the mongoose variable so that it's the same as the the ones in the esm template. 

You'll have to make the change in two places though.

In cli repo: 
https://github.com/code-collabo/node-mongo-cli/blob/e50b1130a91fde85310b10dc0a8a5e9505195890/templates/cjs/src/app.js#L7

And in cjs template: 
https://github.com/code-collabo/node-mongo-cjs-kit/blob/aba7eda3e5a5f9c76bcf0c1bb2766e7ca15a424a/src/app.js#L7

Let me know If you will be willing to take it up or if I should go ahead to fix it myself.

**Comment by KeithanPhilander** [comment]
I am willing but we shall see if I am able.. I'm a noob but let me try.

**Comment by Ifycode** [comment]
Lol... Ok... Assigned to you then. Thanks a lot!
