### ISSUE TITLE
unable to install dependencies

### ISSUE THREAD

**Issue by chuddyjoachim** [code-collabo/node-mongo-cli#73]
"npm install" or "yarn install" cmd throws error and doesn't install dependencies

![Screenshot 2021-05-14 154645](https://user-images.githubusercontent.com/56943504/118339668-64108900-b4ce-11eb-806e-b54d6a37055f.png)

**Comment by Ifycode** [comment]
Taking a look at your screenshot... @chuddyjoachim

**Comment by Ifycode** [comment]
Ok @chuddyjoachim 
Thanks for your patience. I've taken a look at it. You can't use `npm run preinstall` yet since you have not been able to install the dependencies.

The screenshots you sent, the split screen doesn't allow me to see the errors fully. I can't see the affected key and value pair of the bin object. 

Please run the following commands again (full screen this time) so that I can see what's written there fully:

* `npm install` (not npm run preinstall)
* `yarn install`

Separate screenshots in full screen.

**Comment by Ifycode** [comment]
Oh! Wait! I think I know why it doesn't install. It's the pre-install command. The pre-install command automatically runs first once you try to install. The 'bin/customize-preinstall' uses `esm` module which (for you) hasn't been installed yet.

Thank you for helping to detect this. Let me quickly work on this then send you the next set of instructions.

**Comment by Ifycode** [comment]
Ok @chuddyjoachim I just merged in a fix to the develop branch for this. Please do the following:

* Checkout to `develop` branch
* Pull in the new changes - the [git workflow documentation guide](https://code-collabo.gitbook.io/docs/contributor-guide/git-workflow) describes how to go about this in case you need it.

**Comment by Ifycode** [comment]
@all-contributors please add @chuddyjoachim  for bug

**Comment by Ifycode** [comment]
@all-contributors please add @chuddyjoachim for bug
